export const HEADER_TITLE_MAP = {
  '/': '首页',
  '/decorationCases': '装修案例',
  // '/casesDetail': '装修案例详情',
  '/spikeList': '秒杀活动列表',
  // '/spikeDetail': '秒杀活动详情',
  '/mine': '个人中心',
  '/mine/changePersonInfo': '修改个人信息',
  '/findDecorator': '找师傅',
  // '/goodDetail': '商品详情',
  '/shopcar': '购物车',
  '/register': '注册',
  '/login': '登录',
  '/getWechatUserInfo': '微信获取信息',
  '/goodsTypeList': '商品列表',
}
